### ISSUE TITLE
30/03/2023 Viết đặc tả usecase

### ISSUE THREAD

**Issue by vnghia109** [TrnHunhTnPht/Nhom13-DETAI23-API-DASHBOARD#47]
**Task 3 tuần 3:** viết đặc tả usecase, thảo luận và xác định các thành phần chính của ứng dụng

- [ ] Phê duyệt tài khoản người dùng, lấy danh sách người dùng, thêm người dùng, xoá người dùng
- [ ] Hiển thị bảng thống kê, hiển thị biểu đồ, hiển thị bảng dữ liệu
- [x] Các thành phần chính của ứng dụng

**Comment by vnghia109** [comment]
Xác định các thành phần chính của ứng dụng: https://docs.google.com/document/d/1Zefu20VzCWIPYYxN63nFnPJqdUokO4zQgo2XJcnonCs/edit?usp=sharing

**Comment by TrnHunhTnPht** [comment]
[Task 3: Phát](https://docs.google.com/document/d/1e8--_z1sklkeNcmVUG8MBI1TlCpfGVCZaBfdzCwVY6U/edit?usp=sharing)
[Task 3: ĐĂNG]([https://docs.google.com/document/d/1nEH-7JJtSkL7jFS7OazyFtztDfygTkAUoi7xdp5IRbY/edit?usp=sharing](https://docs.google.com/document/d/1nEH-7JJtSkL7jFS7OazyFtztDfygTkAUoi7xdp5IRbY/edit?usp=sharing&fbclid=IwAR2GsMKbsUlUPkUsTv5vOZxg9Ch-29yo47jJMTS4dPuEhbJ5LU3xXp5sCeE))
